# GitHub Funding — add platforms as you enable them.
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [Afraar99]
# patreon: your-patreon-username
# open_collective: your-open-collective-username
# ko_fi: your-ko-fi-username
# buy_me_a_coffee: your-buy-me-a-coffee-username
# custom: ['https://example.com/donate']
