package com.mindful.android.utils

/**
 * Best-effort NSFW search keywords for Accessibility omnibox / `q=` checks.
 *
 * This list is intentionally porn-oriented and is **gameable** (other languages, slang,
 * typos, image search, engines without query params). Known tube hosts in [NsfwDomains]
 * plus hard HOME exit are the primary enforcement for sites; keywords are only a secondary layer.
 */
object NsfwKeywords {
    val keywords = hashSetOf(
        // Explicit / vulgar
        "porn",
        "porno",
        "pornography",
        "pornhub",
        "xxx",
        "xnxx",
        "xvideos",
        "xhamster",
        "redtube",
        "youporn",
        "onlyfans",
        "hentai",
        "nsfw",
        "18+",
        // Acts / genres commonly used for porn search (not general education)
        "blowjob",
        "handjob",
        "deepthroat",
        "creampie",
        "cumshot",
        "facial",
        "anal",
        "threesome",
        "foursome",
        "orgy",
        "gangbang",
        "bdsm",
        "bondage",
        "fetish",
        "hardcore",
        "softcore",
        "milf",
        "stepmom",
        "step sister",
        "stepsister",
        "incest",
        "camgirl",
        "camsex",
        "striptease",
        "stripper",
        "escorts",
        "prostitute",
        "hookup sex",
        "sex video",
        "sex videos",
        "porn video",
        "porn videos",
        "xxx video",
        "xxx videos",
        "nude video",
        "nudes",
        "naked sex",
        "fuck",
        "fucking",
        "boobs",
        "tits",
        "pussy",
        "dick",
        "cock",
        "penis porn",
        "masturbat",
        "orgasm",
        "erotica",
        "erotic",
        "jav ",
        " hentai",
        // Regional / common bypass slang (partial)
        "aunty sex",
        "aunty video",
        "aunty videos",
        "desi sex",
        "desi porn",
        "mms leak",
        "leaked sex",
        "hot sex video",
    )
}
